"""
Django settings for ajira project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import pymysql

pymysql.install_as_MySQLdb()

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b+6-(xm%nv41)4*=i3j#t(4-ik#&ncs*_go_7b)a!woz+&6x*u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'ochomoswill.pythonanywhere.com',
    ]


# Application definition

INSTALLED_APPS = (
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'ajira_ajiriwa',
    'ajira_mwajiri',
    'ajira_jobs',
    'ajira_templates',
    'ajira_parameters',
    'ajira_recommendations',


)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'ajira.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ajira.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ochomoswill$ajira_db',
        'HOST': 'ochomoswill.mysql.pythonanywhere-services.com',
        'PORT': '3306',
        'USER': 'ochomoswill',
        'PASSWORD': 'ajira_5ky302ld',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

#STATIC_URL = '/static/'




STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/ajira_static/'


STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'ajira_static'),
)

#setting up the media file
MEDIA_ROOT = os.path.join(BASE_DIR, 'ajira_media')
MEDIA_URL = '/ajira_media/'


#Sendgrip
# EMAIL_BACKEND = "sgbackend.SendGridBackend"
# SENDGRID_API_KEY = "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"

EMAIL_HOST = 'smtp.webfaction.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'ajira@auranaturals.webfactional.com'
EMAIL_HOST_PASSWORD = '4uranatural5ke@2011'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'ajira@auranaturals.webfactional.com'
SERVER_EMAIL = 'ajira@auranaturals.webfactional.com'
